### ISSUE TITLE
repository

### ISSUE THREAD

**Issue by hedrok** [greatehop/progit2#10]
Кирило: сховище
Олександр: репозиторій
Тарас: Сховище, репозиторій. Давайте чергувати. Обидва ок.

Я залишаю цей issue, бо мені б хотілося узгодити, чи будемо ми чергувати.
Я не проти чергувати, і вже не проти залишити тільки репозиторій.

Олександре, що скажеш?

**Comment by greatehop** [comment]
я не проти чергувати
