### ISSUE TITLE
snapshot

### ISSUE THREAD

**Issue by hedrok** [greatehop/progit2#13]
Кирило, Олександр: знімок
Тарас: То якись русизм здається. Відбиток певно.

Я бачу логіку в пропозиції Тараса: коли повна копія, я дійсно зазвичай використовую відбиток, наприклад "iso disk image" у мене "відбиток". А при використанні snapshot саме йдеться про повну копію... Я тут невпевнений якийсь, якщо Тарас впевнений, та Олександр не проти, я теж не проти "відбитку".

**Comment by greatehop** [comment]
знімок, або снапшот

**Comment by greatehop** [comment]
я не проти "відбитку"
