### ISSUE TITLE
чи перекладаємо коментарі

### ISSUE THREAD

**Issue by tbudurovych** [greatehop/progit2#17]
я тут бачив https://github.com/greatehop/progit2/blame/master/book/03-git-branching/sections/nutshell.asc#L24

там написано `$ git commit -m 'Перша фіксація проекту'` 

мені здається що там де виконуємо команди треба залишати оригінальне ( тобто 'initial commit of my project'), тому що потім важко слідкувати за сумісністю. 

що скажете ?

**Comment by greatehop** [comment]
коментарі пишуться англійскою

**Comment by hedrok** [comment]
Добре, я поверну англійську всюди - я перекладав деінде.

**Comment by tbudurovych** [comment]
домовилися, коментарі залишаєм оригінальні
