### ISSUE TITLE
переклад Branching Workflows

### ISSUE THREAD

**Issue by tbudurovych** [greatehop/progit2#18]
я перекладаю як "Процеси Роботи з Гілками"
що скажете ?

**Comment by hedrok** [comment]
Я, коли контекст дозволяв, уникав прямого перекладу "workflow", а коли не виходило, теж перекладав "Процес Роботи", іноді просто "схеми", наприклад "common workflows to contribute" як "поширені схеми додавання змін до інших проектів"

**Comment by tbudurovych** [comment]
домовилися
