### ISSUE TITLE
ref

### ISSUE THREAD

**Issue by hedrok** [greatehop/progit2#19]
Як би перекласти ref?.. Залишаємо реф?
Я поки що перекладаю "посилання", але мені це не дуже подобається.

**Comment by tbudurovych** [comment]
а дай приклад

**Comment by hedrok** [comment]
Тут https://raw.githubusercontent.com/hedrok/progit2/06-github/book/06-github/sections/3-maintaining.asc є підсекція "Pull Request Refs", автори книги використовують то reference, то ref.
> This tells Git, ``Connect to the `origin` remote, and download the ref named `refs/pull/958/head`.''
Я все перекладав "посилання"...

**Comment by tbudurovych** [comment]
так думаю "посилання" годиться

**Comment by hedrok** [comment]
Добре, залишаю "посилання".
