### ISSUE TITLE
переклад silos

### ISSUE THREAD

**Issue by tbudurovych** [greatehop/progit2#20]
наприклад тут:

https://github.com/greatehop/progit2/blame/master/book/03-git-branching/sections/workflows.asc#L22-L28

я нічо не можу придумати. шось типу ізольована робота ...

**Comment by hedrok** [comment]
http://uk.wikipedia.org/wiki/%D0%95%D0%BB%D0%B5%D0%B2%D0%B0%D1%82%D0%BE%D1%80_(%D0%B7%D0%B5%D1%80%D0%BD%D0%BE%D1%81%D1%85%D0%BE%D0%B2%D0%B8%D1%89%D0%B5)

Чому "ізольована робота"?.. Як я розумію, на елеваторі йде сортування зерна по величині зерен, проходить сушка, і напевно мається на увазі що силос/зерносховище/башта master - це вже сухе/необхідного розміру зерно, а в башті develop занадто вогке/велике.
Це переважно моя уява, проте я зрозумів так.

Не знаю наскільки пересічному програмісту буде зрозуміло "елеватор"...

Оскільки це слово зустрічається тільки на цій сторінці та один раз в https://raw.githubusercontent.com/hedrok/progit2/06-github/book/05-distributed-git/sections/contributing.asc#571 і точно не є терміном, я пропоную "зерносховище".

Не подобається - буду ще думати :)

**Comment by tbudurovych** [comment]
я ніколи не був на елеваторі :) пришли фотки як це виглядає

--
Best Regards, Taras Budurovych

9 червня 2015 р. 17:14 Kyrylo Yatsenko <notifications@github.com> написав:

**Comment by hedrok** [comment]
Ну, ось: https://www.google.com.ua/search?q=елеватор&client=ubuntu&hs=Tsw&channel=fs&tbm=isch&tbo=u&source=univ&sa=X&ved=0CCIQsARqFQoTCOqEmNXJhMYCFYboLAod0BoJgg&biw=1920&bih=968
:)

Я теж ніколи не був на елеваторі :)

**Comment by tbudurovych** [comment]
Дійсно фотки схожі на git :)

//taras

**Comment by tbudurovych** [comment]
використовую "елеватор"
