### ISSUE TITLE
Створення офіційного репозиторію для [uk]

### ISSUE THREAD

**Issue by VBoden** [greatehop/progit2#24]
Доброго дня усім!
А хтось писав цьому @schacon щоб створили офіційний репозиторій і внесли українську мову у список перекладів? Бо я поглянув статистику перекладів по інших мовах і там є взагалі низькі відсотки. Може їх треба трішки подіставати, щоб створили? Бо може бути ситуація, що інші команди також будуть перекладати (уже перекладене). Я сам тільки випадково натрапив на цю вітку.

**Comment by hedrok** [comment]
For @schacon: If you read this thread: VBoden asked, whether we asked you to add Ukrainian translation to list of translations. We did, here: https://github.com/progit/progit2/issues/304
If you can, please add it: we worked a lot, and translated a lot :)
In the rest of message, I answer his question and i'm telling VBoden about our workflow and ask him to join our efforts in translating progit2 to Ukrainian.

Доброго дня, Володимире!
З 10 травня просимо... https://github.com/progit/progit2/issues/304
Здається, на превеликий жаль, schacon ігнорує нас :(
Ми тут перекладаємо, ніхто про це не знає...
Якщо в тебе є якісь інші методи попросити створити офіційний репозиторій та додати українську мову до списку перекладів, будемо дуже вдячні :)

Якщо є бажання приєднатися: головне сховище це, щоб було простіше ми просто роздали по розділу кожному і потихеньку їх перекладаємо. Наступний вільний розділ восьмий.
Якщо бажаєш взяти, напиши тут.

Словничок термінів тут: https://github.com/greatehop/progit2/issues/14
Інші: https://github.com/greatehop/progit2/issues
Для обговорення термінів можеш створювати тут issue.

**Comment by VBoden** [comment]
А на пошту особистого листа не писали? Може він не читатє там.
Так,  я візьму восьмий розділ.

**Comment by hedrok** [comment]
Слушна думка. Відправив листа. Може допоможе.

**Comment by VBoden** [comment]
Я вибачаюсь, що набридаю, але він щось відповів чи ігнорує?

**Comment by hedrok** [comment]
:) Я відразу напишу, щойно отримаю відповідь :) Чесне слово ) Навіть спам перевірив зараз.
Тобто ігнорує.

**Comment by VBoden** [comment]
Там уже є також запитання про створення репо для перекладу на грецьку і ось що там відповіли про вимоги: 
"Yes, you have to start translating at least the first chapter. Then ping schacon (Scott Chacon, one of the authors) who has the right to set up your repo for publication, and be patient. Scott is very busy, so things may take time. Add changes also to the git/git-scm.com to add an entry for Greek in the book section". 
Можливо ще довго прийдеться почекати( Тільки от хтось розуміє останнє речення?

**Comment by hedrok** [comment]
Останнє речення напевно про https://github.com/git/git-scm.com
Можливо ми там можемо самостійно додати свій український переклад (там вже є український переклад першого розділу першого видання книжки) - це треба буде подивитись.

**Comment by greatehop** [comment]
Схоже, що номер з email не пройшов, чи лист потрапив до /dev/null :)
Написав @schacon до твиттера.

**Comment by tbudurovych** [comment]
спрацювало мабуть

--
Best Regards, Taras Budurovych

26 серпня 2015 р. 10:49 Alexander Gubanov <notifications@github.com>
написав:

**Comment by greatehop** [comment]
ура!
