### ISSUE TITLE
Компіляція в pdf

### ISSUE THREAD

**Issue by VBoden** [greatehop/progit2#25]
А хтось компілював у пдф формат? У мене замість слів - порожні місця. Вичитав, що це шрифти для кирилиці не підходять, але все ж таки не зміг вирішити проблему. Може хтось зміг розібратись із цим? Чи це можливо лише на Лінукс такі проблеми?

**Comment by VBoden** [comment]
Проблема пофіксилась оновленням версії asciidoctor-pdf (можливо комусь це цікаво): https://github.com/VBoden/progit2/commit/61be566e820bd112ad4a6fb468df1f9edff53d99

**Comment by hedrok** [comment]
Я не компілював, дякую за інформацію. Напиши вже версію, з якою не працювало і з якою запрацювало - тоді буде точно корисно )

**Comment by VBoden** [comment]
Не працювало з asciidoctor-pdf версії 1.5.0.alpha.5 та asciidoctor версії 1.5.0, працює з asciidoctor-pdf версії 1.5.0.alpha.8 та asciidoctor версії 1.5.2. Якщо не помиляюсь (щось таке вичитав на форумах), то саме у asciidoctor-pdf версії 1.5.0.alpha.8 ця проблема була вирішена.

**Comment by hedrok** [comment]
Дуже дякую. Закривай тоді напевно issue.
