### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by hedrok** [greatehop/progit2#7]
Кирило: мітка, теґ, позначка
Олександр: тег, проти ґ

Готовий підтримати рішення Тараса щодо тег/теґ

lightweight (tag) - легкий, чи може простий?..
annotated (tag) - анотований

**Comment by tbudurovych** [comment]
я за тег/Теґ, мітка. всі годяться.
позначка не дуже.
про ґ - не принципово.

lightweight (tag) - легкий

**Comment by greatehop** [comment]
tag - тег
lightweight (tag) - легкий тег
annotated (tag) - анотований тег

**Comment by hedrok** [comment]
Гадаю розумно ми це не вирішимо і ніякого сенсу доводити важливість літери ґ не має.
Олександре, пропоную тобі підкинути монетку, якщо тризуб - теґ, якщо ні - тег. Я тобі довіряю :)

**Comment by greatehop** [comment]
підкинув - теґ
