### ISSUE TITLE
commit

### ISSUE THREAD

**Issue by hedrok** [greatehop/progit2#8]
Кирило: фіксація, коміт
Тарас: коміт

to commit: уникати, тобто писати не "закомітити", а "зробити коміт".

Олександре, ти погоджуєшся на одну "м"?..

**Comment by tbudurovych** [comment]
думаю тут одна М.

в рос мові з 2ма.
i.e. communism - комунізм - коммунизм
comma - кома - комма

**Comment by greatehop** [comment]
коміт
